### ISSUE TITLE
Parameters are reset to default when re-opening GUI window

### ISSUE THREAD

**Issue by unfa** [x42/fat1.lv2#4] opened 2017-02-19 18:57 UTC
I often set up Autotune in Ardour 5 to measure vocal performance quality while recording, and combing the final result - my Correction strength parameter is always at 0 - I don't want tuning, just measurement.

I loose the Autotune window, and can lo loger see it's readings, so I reopen the GUI window from Ardour's track plugin list.

Then I realise that Autotune's correction is enabled, tuning my vocals, while I'm trying to asses their raw quality (d'oh!).

I did some tests and all parameters excluding the Auto/MIDI/Manual mode are reset to default.
It also behaves the same way when run in Carla plugin host.

**Comment by x42** [comment] 2017-02-19 20:21
duplicate of #3 ;  already fixed in 7809fab (x42-plugins-20161230)

**Closed as completed by x42** 2017-02-19 20:21 UTC

**Comment by unfa** [comment] 2017-02-20 18:47
Thanks! Maybe it'd be good to push the update to KX Studio repositories?

**Comment by x42** [comment] 2017-02-20 20:11
They should be up-to-date already.  At least falktx pinged me on the day of the release.
